### PR TITLE
Test pixi package manager

### PR DESCRIPTION
**Pull request by jorisv**
Test pixi package manager to ease CI steps and help new developers.
Also, fix cache use for ccache.,

- [x] Create pixi.toml
- [x] Test CI
- [x] Test conda recipe build
- [x] Check ccache cache
- [x] Update README.md

Pro:
- Lock file make CI build faster
- prefix-dev/setup-pixi cache make CI build faster
- Dependencies are well documented
- New developer can easily build the project
- Pixi is connected to the CI and **must** be maintained
- No need to install anaconde (pixi package it)

Con:
- New tool to install and learn

### CODE REVIEW

**Comment by ManifoldFR** [comment]
What are we doing with this ? Since we've got it on eigenpy now

**Comment by jorisv** [comment]
It's still not merged on eigenpy.

I have a last check to do: is it convenient to work with multiple source project and pixi ?

**Comment by ManifoldFR** [comment]
Is this still supposed to be opened after #113 was merged ?

**Comment by jorisv** [comment]
Oh boy, I forget this one !
We can close it :)

**Pull request closed without merging**
